# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6d7358df22b678ac156c41d6c5b0c5c9cefc673655373b778a0f3a48cb5a770ecc158ae86d45ebe1cc0ad144173a1dfd7e5f1ea436fbd1283bd8493b970e0b

test:
  secret_key_base: 12e965c9099c6afb9c7844861d0c1aaf41ac574515fd2dc4e3d76c112d404f1effd6603bffcb1c7ab5fd04fc00580ca824940803e6c4fce093b5eb2ecff5386f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
